### PR TITLE
Add checkstyle / Android lint plugin to DangerJS

### PR DESCRIPTION
**Pull request by damian-burke**

### CODE REVIEW

**Comment by damian-burke** [comment]
Added a second commit after making the plugin a bit more "generic". Instead of just parsing ktlint reports, it can now parse checkstyle reports and Android lint reports.

**Review by Rouby — APPROVED** [review]

**Comment by damian-burke** [comment]
@gianluz (pinging you since you merged the last commit) Not sure if I forgot to add something here or if I should ping someone to get this merged. 🤔 Otherwise I can also close the PR if it's not the right place?

**Comment by gianluz** [comment]
I'm happy with the new plugin! Since is not for danger kotlin but for danger js last word to @orta ?

**Comment by orta** [comment]
👍🏻

**Pull request merged**
